import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {deflateSync} from 'node:zlib';
import {createTestDatabase} from './helpers/d1.js';
import {handleApiRequest} from '../worker/src/index.js';
import {accessEnv,accessToken,accessJwks} from './helpers/access.js';
import {defaultLayout,validDocument,validItems} from '../frontend/admin/studio/model.js';
import {wrapText} from '../frontend/admin/studio/canvas.js';
import {makeZip,crc32} from '../frontend/admin/studio/zip.js';
import {validatePng} from '../worker/src/handlers/image-studio.js';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
function png(){
 const chunk=(name,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(name,4);data.copy(b,8);b.writeUInt32BE(crc32(b.subarray(4,-4)),b.length-4);return b;};
 const header=Buffer.alloc(13);header.writeUInt32BE(1080);header.writeUInt32BE(1350,4);header[8]=8;header[9]=6;
 return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',deflateSync(Buffer.alloc((1080*4+1)*1350))),chunk('IEND',Buffer.alloc(0))]);
}
test('isolated workerd D1 batch and private R2 complete the image round-trip',async t=>{
 const bundle=await build({entryPoints:[new URL('../worker/src/index.js',import.meta.url).pathname.replace(/^\/([A-Z]:)/,'$1')],bundle:true,format:'esm',platform:'browser',write:false});
 const mf=new Miniflare(convertV4MiniflareOptions({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-08-31',d1Databases:['DB'],r2Buckets:['STUDIO_IMAGES'],bindings:{APP_ENV:'development',ADMIN_AUTH_PROVIDER:'dev',DEV_ADMIN_MODE:'true',DEV_ADMIN_TOKEN:'isolated-local-runtime-test-token',IMAGE_STUDIO_ENABLED:'true'}}));
 t.after(()=>mf.dispose());const db=await mf.getD1Database('DB');
 for(const name of ['0001_create_submissions','0002_create_admin_auth','0004_add_local_admin_auth','0005_add_access_email','0006_access_only_admins','0007_image_drafts'])await db.exec(readFileSync(new URL(`../migrations/${name}.sql`,import.meta.url),'utf8').replace(/^--.*$/gm,'').replace(/[\r\n]/g,' '));
 await db.prepare("INSERT INTO submissions(id,content) VALUES(1,'runtime draft')").run();
 const url='http://localhost/api/admin',headers={Authorization:'Bearer isolated-local-runtime-test-token'};
 assert.equal((await mf.dispatchFetch(url+'/submissions/1/approve',{method:'POST',headers})).status,200);
 assert.equal(await db.prepare('SELECT COUNT(*) n FROM image_drafts').first('n'),1);
 const uploaded=await mf.dispatchFetch(url+'/studio/drafts/1/ready',{method:'POST',headers:{...headers,'Content-Type':'image/png','If-Match':'1'},body:png()});
 assert.equal(uploaded.status,200);const version=(await uploaded.json()).data.versionId;
 const image=await mf.dispatchFetch(url+'/studio/images/'+version,{headers});assert.equal(image.status,200);assert.deepEqual(Buffer.from(await image.arrayBuffer()),png());
 assert.equal((await mf.dispatchFetch(url+'/studio/images/'+version)).status,401);
 const bucket=await mf.getR2Bucket('STUDIO_IMAGES');assert.equal((await bucket.list()).objects.length,1);
 assert.deepEqual((await db.prepare('PRAGMA foreign_key_check').all()).results,[]);
});
async function setup(t,role='owner'){
 const db=createTestDatabase({images:true});t.after(()=>db.close());
 db.raw.exec("INSERT INTO admins(id,github_user_id,github_username,access_email,role) VALUES(1,'123','original-owner','owner@example.com','owner'); INSERT INTO submissions(id,content) VALUES(1,'原始投稿'),(2,'第二篇');");
 if(role!=='owner')db.raw.exec(`INSERT INTO admins(id,access_email,role) VALUES(2,'friend@example.com','${role}')`);
 const objects=new Map();
 const env={...accessEnv,DB:db.DB,APP_ENV:'production',ADMIN_AUTH_PROVIDERS:'access',ACCESS_AUTH_ENABLED:'true',LOCAL_AUTH_ENABLED:'false',SESSION_SECRET:'test-secret-more-than-thirty-two-characters',IMAGE_STUDIO_ENABLED:'true',STUDIO_IMAGES:{async put(key,value){objects.set(key,value);},async get(key){const body=objects.get(key);return body?{body}:null;}}};
 const call=(path,options={},override={})=>handleApiRequest(new Request('https://admin.example.test'+path,options),{...env,...override},{accessJwks});
 const login=await call('/api/auth/access',{headers:{'Cf-Access-Jwt-Assertion':await accessToken({email:role==='owner'?'owner@example.com':'friend@example.com'})}});
 const cookie=login.headers.get('set-cookie').split(';')[0];
 const session=(await (await call('/api/auth/me',{headers:{Cookie:cookie}})).json()).data;
 const headers={Cookie:cookie,'X-CSRF-Token':session.csrfToken,Origin:'https://admin.example.test'};
 const req=async(path,method='GET',data,extra={})=>call(path,{method,headers:{...headers,...(data?{'Content-Type':'application/json'}:{}),...extra},...(data?{body:JSON.stringify(data)}:{})});
 const studio=(path,method,data)=>req('/api/admin/studio'+path,method,data);
 const ready=async(id,revision)=>call(`/api/admin/studio/drafts/${id}/ready`,{method:'POST',headers:{...headers,'Content-Type':'image/png','If-Match':String(revision)},body:png()});
 return {db,env,objects,call,req,studio,ready,headers};
}
test('0007 preserves populated identities, submissions, sessions, audits and constraints',t=>{
 const db=createTestDatabase();t.after(()=>db.close());
 db.raw.exec("INSERT INTO admins(id,github_user_id,github_username,access_email,role) VALUES(1,'123','owner','owner@example.com','owner'); INSERT INTO submissions(id,content,status) VALUES(1,'legacy','approved'); INSERT INTO audit_logs(admin_id,action,submission_id) VALUES(1,'approve_submission',1)");
 db.raw.prepare('INSERT INTO admin_sessions(token_hash,admin_id,expires_at) VALUES(?,1,?)').run('a'.repeat(64),'2099-01-01T00:00:00Z');
 const tables=['admins','submissions','admin_sessions','audit_logs'];const before=tables.map(table=>db.raw.prepare(`SELECT * FROM ${table}`).all());
 db.raw.exec(readFileSync(new URL('../migrations/0007_image_drafts.sql',import.meta.url),'utf8'));
 assert.deepEqual(tables.map(table=>db.raw.prepare(`SELECT * FROM ${table}`).all()),before);assert.deepEqual(db.raw.prepare('PRAGMA foreign_key_check').all(),[]);
 assert.throws(()=>db.raw.exec("INSERT INTO image_drafts(id,text,layout) VALUES(999,'x','{}')"));
 assert.equal(db.raw.prepare('SELECT count(*) n FROM image_drafts').get().n,0);
});
for(const role of ['owner','admin','moderator'])test(`${role} can approve, edit, publish private image and prepare dispatch; roster remains owner-only`,async t=>{
 const {db,req,studio,ready,call,objects}=await setup(t,role);
 assert.equal((await req('/api/admin/submissions/1/approve','POST')).status,200);
 assert.equal(db.raw.prepare('SELECT count(*) n FROM image_drafts').get().n,1);
 assert.equal((await req('/api/admin/submissions/1/approve','POST')).status,409);
 let draft=(await (await studio('/drafts/1')).json()).data;
 const original=db.raw.prepare('SELECT content FROM submissions WHERE id=1').get().content;
 draft=(await (await studio('/drafts/1','PUT',{revision:draft.revision,text:'改過的圖片文字'.repeat(20),layout:defaultLayout()})).json()).data;
 assert.equal(draft.revision,2);assert.equal(db.raw.prepare('SELECT content FROM submissions WHERE id=1').get().content,original);
 const published=await ready(1,2);assert.equal(published.status,200);const version=(await published.json()).data.versionId;
 assert.equal(objects.size,1);assert.equal((await req('/api/admin/studio/images/'+version)).status,200);
 assert.equal((await call('/api/admin/studio/images/'+version)).status,401);
 assert.equal((await req('/api/admin/admins')).status,role==='owner'?200:403);
 const response=await studio('/dispatches','POST',{revision:0,caption:'貼文說明',items:[version]});assert.equal(response.status,200);
 const dispatch=(await response.json()).data;assert.equal(dispatch.items[0].version_id,version);
 assert.equal((await ready(1,2)).status,409);
 assert.equal((await studio('/drafts/1','PUT',{revision:3,text:'新版本',layout:defaultLayout()})).status,200);
 const next=(await (await ready(1,4)).json()).data.versionId;
 const saved=(await (await studio('/dispatches/'+dispatch.id)).json()).data;
 assert.equal(saved.items[0].version_id,version);assert.equal(saved.items[0].latest_version_id,next);
 assert.throws(()=>db.raw.exec("UPDATE image_versions SET text='changed'"));
 assert.deepEqual(db.raw.prepare('PRAGMA foreign_key_check').all(),[]);
});
test('approval and image creation roll back together; old approved drafts are idempotent',async t=>{
 const {db,req,studio}=await setup(t);
 db.raw.exec("CREATE TRIGGER fail_image BEFORE INSERT ON image_drafts BEGIN SELECT RAISE(ABORT,'test failure'); END;");
 assert.equal((await req('/api/admin/submissions/1/approve','POST')).status,500);
 assert.equal(db.raw.prepare('SELECT status FROM submissions WHERE id=1').get().status,'pending');
 assert.equal(db.raw.prepare("SELECT count(*) n FROM audit_logs WHERE action='approve_submission'").get().n,0);
 db.raw.exec("DROP TRIGGER fail_image; UPDATE submissions SET status='approved' WHERE id=1;");
 assert.equal((await studio('/drafts/1','POST')).status,200);assert.equal((await studio('/drafts/1','POST')).status,200);
 assert.equal(db.raw.prepare('SELECT count(*) n FROM image_drafts').get().n,1);
 assert.equal((await studio('/drafts/2','POST')).status,404);
});
test('revision conflicts, CSRF, disabled accounts and storage failures fail closed',async t=>{
 const {db,req,studio,call,headers,ready,env}=await setup(t);
 await req('/api/admin/submissions/1/approve','POST');
 assert.equal((await studio('/drafts/1','PUT',{revision:9,text:'x',layout:defaultLayout()})).status,409);
 assert.equal((await call('/api/admin/studio/drafts/1',{method:'PUT',headers:{Cookie:headers.Cookie}})).status,403);
 env.STUDIO_IMAGES.put=async()=>{throw new Error('storage failed');};assert.equal((await ready(1,1)).status,500);
 assert.equal(db.raw.prepare('SELECT state FROM image_drafts').get().state,'draft');assert.equal(db.raw.prepare('SELECT count(*) n FROM image_versions').get().n,0);
 assert.equal((await call('/api/admin/studio',{headers},{IMAGE_STUDIO_ENABLED:'false'})).status,503);
 db.raw.exec("INSERT INTO admins(access_email,role) VALUES('other@example.com','owner'); UPDATE admins SET enabled=0 WHERE id=1");
 assert.equal((await studio('')).status,401);
});
test('dispatch enforces count, uniqueness, order, limits, revisions and atomic audit',async t=>{
 const {db,req,studio,ready}=await setup(t);
 for(const id of [1,2])await req(`/api/admin/submissions/${id}/approve`,'POST');
 const a=(await (await ready(1,1)).json()).data.versionId,b=(await (await ready(2,1)).json()).data.versionId;
 for(const items of [[],[a,a],Array(11).fill(a)])assert.equal((await studio('/dispatches','POST',{revision:0,caption:'',items})).status,400);
 assert.equal((await studio('/dispatches','POST',{revision:0,caption:'x'.repeat(2001),items:[a]})).status,400);
 let d=(await (await studio('/dispatches','POST',{revision:0,caption:'說明',items:[b,a]})).json()).data;
 assert.deepEqual(d.items.map(i=>i.version_id),[b,a]);
 assert.equal((await studio('/dispatches/'+d.id,'PUT',{revision:99,caption:'stale',items:[a]})).status,409);
 db.raw.exec("CREATE TRIGGER fail_dispatch_audit BEFORE INSERT ON audit_logs WHEN NEW.action='dispatch_saved' BEGIN SELECT RAISE(ABORT,'audit failed'); END;");
 assert.equal((await studio('/dispatches/'+d.id,'PUT',{revision:1,caption:'new',items:[a,b]})).status,500);
 d=(await (await studio('/dispatches/'+d.id)).json()).data;assert.equal(d.revision,1);assert.deepEqual(d.items.map(i=>i.version_id),[b,a]);
});
test('failed image audit retains previous version and rolls back ready transition',async t=>{
 const {db,req,studio,ready}=await setup(t);await req('/api/admin/submissions/1/approve','POST');
 const previous=(await (await ready(1,1)).json()).data.versionId;
 await studio('/drafts/1','PUT',{revision:2,text:'next',layout:defaultLayout()});
 db.raw.exec("CREATE TRIGGER fail_ready_audit BEFORE INSERT ON audit_logs WHEN NEW.action='image_ready' BEGIN SELECT RAISE(ABORT,'audit failed'); END;");
 assert.equal((await ready(1,3)).status,500);
 assert.equal(db.raw.prepare('SELECT revision FROM image_drafts').get().revision,3);
 assert.equal(db.raw.prepare('SELECT count(*) n FROM image_versions').get().n,1);
 assert.equal((await req('/api/admin/studio/images/'+previous)).status,200);
 db.raw.exec('DROP TRIGGER fail_ready_audit');assert.equal((await ready(1,3)).status,200);
});
test('text document, Unicode wrapping, PNG integrity and deterministic ZIP',async()=>{
 const manual=defaultLayout();manual.number.label='110';assert.equal(validDocument('文字',manual),true);
 manual.number.label='invalid';assert.equal(validDocument('文字',manual),false);
 delete manual.number.label;assert.equal(validDocument('文字',manual),true);
 assert.equal(validDocument('👨‍👩‍👧‍👦'.repeat(1000),defaultLayout()),true);assert.equal(validDocument('x'.repeat(1001),defaultLayout()),false);
 assert.equal(validDocument('text',{...defaultLayout(),evil:{}}),false);assert.equal(validItems([]),false);
 assert.deepEqual(wrapText('中e\u0301👨‍👩‍👧‍👦\n第二行',()=>1,650),['中e\u0301👨‍👩‍👧‍👦','第二行']);
 assert.deepEqual(wrapText('abcd',s=>s.length,2),['ab','cd']);
 const image=png();validatePng(image);const broken=image.slice();broken[25]^=1;assert.throws(()=>validatePng(broken));assert.throws(()=>validatePng(image.subarray(0,50)));
 const blob=makeZip([['01.png',image],['caption.txt','中文說明']]);const bytes=new Uint8Array(await blob.arrayBuffer());assert.equal(new DataView(bytes.buffer).getUint32(0,true),0x04034b50);assert.ok(new TextDecoder().decode(bytes).includes('caption.txt'));
});
