import {
  cp,
  mkdir,
  readFile,
  rm,
  writeFile
} from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, "..");
const DEFAULT_OUTPUT_DIRECTORY = resolve(projectRoot, ".pages-dist");

function requireHttpsUrl(name, value, { originOnly = false } = {}) {
  if (!value) {
    throw new Error(`${name} is required.`);
  }

  let url;
  try {
    url = new URL(value);
  } catch {
    throw new Error(`${name} must be a valid URL.`);
  }

  if (
    url.protocol !== "https:"
    || url.username
    || url.password
    || url.search
    || url.hash
  ) {
    throw new Error(`${name} must be a public HTTPS URL without credentials, query, or hash.`);
  }

  if (originOnly && url.pathname !== "/") {
    throw new Error(`${name} must be an origin without a path.`);
  }

  return url;
}

function replaceOnce(source, pattern, replacement, label) {
  const matches = source.match(new RegExp(pattern.source, pattern.flags.includes("g")
    ? pattern.flags
    : `${pattern.flags}g`));
  if (matches?.length !== 1) {
    throw new Error(`Expected exactly one ${label}; found ${matches?.length ?? 0}.`);
  }
  return source.replace(pattern, replacement);
}

function productionConfig(apiOrigin) {
  return [
    "// Generated by scripts/build-pages.js for the GitHub Pages artifact.",
    "// This file is public and must never contain secrets.",
    "window.APP_CONFIG = Object.freeze({",
    `  API_BASE_URL: ${JSON.stringify(apiOrigin)},`,
    '  ADMIN_AUTH_MODE: "github"',
    "});",
    ""
  ].join("\n");
}

function productionHtml(source, { apiOrigin, socialImage }) {
  const csp = `connect-src 'self' ${apiOrigin};`;
  const withCsp = replaceOnce(
    source,
    /connect-src [^;]+;/,
    csp,
    "connect-src CSP directive"
  );
  return withCsp.replaceAll(
    "http://127.0.0.1:8787/og.png",
    () => socialImage
  );
}

function escapeHtmlAttribute(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function adminRedirectHtml(apiOrigin) {
  const adminUrl = escapeHtmlAttribute(new URL("/admin/", apiOrigin).href);
  return `<!doctype html>
<html lang="zh-Hant">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex,nofollow">
    <meta name="referrer" content="no-referrer">
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; base-uri 'none'; form-action 'none'">
    <meta http-equiv="refresh" content="0; url=${adminUrl}">
    <title>前往管理後台</title>
  </head>
  <body>
    <p><a href="${adminUrl}" rel="noreferrer">前往安全管理後台</a></p>
  </body>
</html>
`;
}

export async function buildPages({
  apiBaseUrl,
  siteUrl,
  sourceDirectory = resolve(projectRoot, "frontend"),
  outputDirectory = DEFAULT_OUTPUT_DIRECTORY
}) {
  const apiUrl = requireHttpsUrl("PAGES_API_BASE_URL", apiBaseUrl, {
    originOnly: true
  });
  const frontendUrl = requireHttpsUrl("PAGES_SITE_URL", siteUrl);
  if (!frontendUrl.pathname.endsWith("/")) {
    throw new Error("PAGES_SITE_URL must end with a slash.");
  }

  const source = resolve(sourceDirectory);
  const output = resolve(outputDirectory);
  if (output === source || output === projectRoot) {
    throw new Error("Refusing to overwrite the source or project root.");
  }

  await rm(output, { recursive: true, force: true });
  await mkdir(output, { recursive: true });
  await cp(source, output, {
    recursive: true,
    filter: (path) => !basename(path).startsWith("._") && basename(path) !== ".DS_Store"
  });

  const apiOrigin = apiUrl.origin;
  const socialImage = new URL("og.png", frontendUrl).href;
  await writeFile(
    join(output, "config.js"),
    productionConfig(apiOrigin),
    "utf8"
  );

  for (const relativePath of ["index.html"]) {
    const path = join(output, relativePath);
    const html = await readFile(path, "utf8");
    await writeFile(path, productionHtml(html, { apiOrigin, socialImage }), "utf8");
  }

  // GitHub Pages hosts only the public submission UI. Keep /admin/ as a
  // no-script handoff to the Worker-hosted, same-origin admin application.
  await rm(join(output, "admin"), { recursive: true, force: true });
  await mkdir(join(output, "admin"), { recursive: true });
  await writeFile(
    join(output, "admin/index.html"),
    adminRedirectHtml(apiOrigin),
    "utf8"
  );
  await rm(join(output, "assets/admin.js"), { force: true });
  await rm(join(output, "assets/admin-auth.js"), { force: true });

  const contentPath = join(output, "content.json");
  const content = JSON.parse(await readFile(contentPath, "utf8"));
  content.social = { ...content.social, image: socialImage };
  await writeFile(contentPath, `${JSON.stringify(content, null, 2)}\n`, "utf8");

  return Object.freeze({ apiOrigin, frontendUrl: frontendUrl.href, output });
}

async function main() {
  const result = await buildPages({
    apiBaseUrl: process.env.PAGES_API_BASE_URL,
    siteUrl: process.env.PAGES_SITE_URL,
    outputDirectory: process.env.PAGES_OUTPUT_DIR
      ? resolve(process.env.PAGES_OUTPUT_DIR)
      : DEFAULT_OUTPUT_DIRECTORY
  });
  console.log(`GitHub Pages artifact prepared at ${result.output}.`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
